import type { VersionsSet } from '../lib/index.ts'
import { strict as assert } from 'node:assert'
import { test } from 'node:test'
import { diffDependencySets, findLockfileLine, parseLockfile, parseNpmLock, parsePnpmLock, parseYarnBerryLock, parseYarnV1Lock, yarnBerrySpecifierToName, yarnV1SpecifierToName } from '../lib/index.ts'

function toSorted(obj: VersionsSet): Record<string, string[]> {
  const out: Record<string, string[]> = {}
  for (const [k, v] of obj) out[k] = Array.from(v).sort()
  return Object.fromEntries(Object.entries(out).sort(([a], [b]) => a.localeCompare(b)))
}

const packageLockJson = JSON.stringify({
  name: 'example',
  lockfileVersion: 3,
  packages: {
    '': { name: 'example', version: '1.0.0' },
    'node_modules/lodash': { version: '4.17.21' },
    'node_modules/@scope/name': { version: '2.3.4' },
  },
})

const pnpmLock = `lockfileVersion: 9.0

packages:

  /lodash@4.17.21:
    resolution: {integrity: sha512-...}

  /@scope/name@2.3.4(peer@1):
    resolution: {integrity: sha512-...}
`

const yarnV1Lock = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"

"@scope/name@^2.3.4":
  version "2.3.4"
`

const yarnBerryLock = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"

"@scope/name@npm:^2.3.4":
  version: 2.3.4
`

test('parse npm package-lock.json', () => {
  const res = parseNpmLock(packageLockJson)
  assert.deepEqual(toSorted(res), {
    '@scope/name': ['2.3.4'],
    'lodash': ['4.17.21'],
  })
})

test('parse pnpm pnpm-lock.yaml minimal', () => {
  const res = parsePnpmLock(pnpmLock)
  assert.deepEqual(toSorted(res), {
    '@scope/name': ['2.3.4'],
    'lodash': ['4.17.21'],
  })
})

test('parse yarn v1 yarn.lock minimal', () => {
  const res = parseYarnV1Lock(yarnV1Lock)
  assert.deepEqual(toSorted(res), {
    '@scope/name': ['2.3.4'],
    'lodash': ['4.17.21'],
  })
})

test('parse yarn berry yarn.lock minimal', () => {
  const res = parseYarnBerryLock(yarnBerryLock)
  assert.deepEqual(toSorted(res), {
    '@scope/name': ['2.3.4'],
    'lodash': ['4.17.21'],
  })
})

test('parseLockfile dispatch', () => {
  const npm = parseLockfile('package-lock.json', '{"packages":{}}')
  const pnpm = parseLockfile('pnpm-lock.yaml', `packages:\n`)
  const yarnV1 = parseLockfile('yarn.lock', `pkg@^1:\n  version "1.0.0"`)
  const yarnBerry = parseLockfile('yarn.lock', `"pkg@npm:^1":\n  version: 1.0.0`)
  assert.ok(npm instanceof Map && pnpm instanceof Map && yarnV1 instanceof Map && yarnBerry instanceof Map)
})

test('yarn V1 specifier to name', () => {
  assert.equal(yarnV1SpecifierToName('lodash@^4.17.21'), 'lodash')
  assert.equal(yarnV1SpecifierToName('@scope/name@^1.0.0'), '@scope/name')
  assert.equal(yarnV1SpecifierToName('name@npm:^1.0.0'), 'name')
})

test('yarn Berry specifier to name', () => {
  assert.equal(yarnBerrySpecifierToName('lodash@npm:^4.17.21'), 'lodash')
  assert.equal(yarnBerrySpecifierToName('@scope/name@npm:^1.0.0'), '@scope/name')
  assert.equal(yarnBerrySpecifierToName('name@npm:^1.0.0'), 'name')
})

test('diffDependencySets identifies changes', () => {
  const a: VersionsSet = new Map([['lodash', new Set(['4.17.21'])]])
  const b: VersionsSet = new Map([['lodash', new Set(['4.17.21', '4.17.22'])]])
  const diff = diffDependencySets(a, b)
  assert.equal(diff.length, 1)
  assert.equal(diff[0].name, 'lodash')
})

test('findLockfileLine finds lines in lockfiles', () => {
  assert.equal(
    findLockfileLine('package-lock.json', packageLockJson, 'lodash', '4.17.21'),
    1, // version: 4.17.21
  )
  assert.equal(
    findLockfileLine('pnpm-lock.yaml', pnpmLock, 'lodash', '4.17.21'),
    5, // resolution: {integrity: sha512-...}
  )
  assert.equal(
    findLockfileLine('yarn.lock', yarnV1Lock, 'lodash', '4.17.21'),
    6, // resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
  )
  assert.equal(
    findLockfileLine('yarn.lock', yarnBerryLock, 'lodash', '4.17.21'),
    9, // resolution: "lodash@npm:4.17.21"
  )
})
