name: 'Provenance downgrade check'
description: 'Detect and fail CI when dependencies in your lockfile lose npm provenance or trusted publisher status.'
author: 'Daniel Roe (@danielroe)'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'shield'
  color: 'purple'

inputs:
  lockfile:
    description: 'Path to lockfile (pnpm-lock.yaml, package-lock.json, yarn.lock)'
    required: false
  workspace-path:
    description: 'Path to workspace root (default: GITHUB_WORKSPACE)'
    required: false
    default: '.'
  base-ref:
    description: 'Git ref to compare against (e.g., origin/main)'
    required: false
  fail-on-downgrade:
    description: 'Fail behavior: true|false|any|only-provenance-loss (default: true)'
    required: false
    default: 'true'
  fail-on-provenance-change:
    description: 'Fail job when provenance repository/branch changes (default: false)'
    required: false
    default: 'false'

outputs:
  downgraded:
    description: 'JSON array of { name, from, to, downgradeType } for detected downgrades'
  changed:
    description: 'JSON array of provenance change events: { name, from, to, type, previousRepository?, newRepository?, previousBranch?, newBranch? }'

runs:
  using: node24
  main: lib/index.ts
